version: '2'
services:
    lab1_1-app:
        image: lab1_1
        external_links:
            - lab1_1-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=lab1_1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lab1_1-mongodb:
        extends:
            file: mongodb.yml
            service: lab1_1-mongodb
