version: '2'
services:
    lab1_1-mongodb:
        container_name: lab1_1-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/lab1_1/mongodb/:/data/db/
